//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolOperaciones
    {
        public int id { get; set; }
        public int Id_operacion { get; set; }
        public int Id_rol { get; set; }
    
        public virtual Operaciones Operaciones { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
