//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int id_usuario { get; set; }

        internal static object ReadLine()
        {
            throw new NotImplementedException();
        }

        public string nombre { get; set; }
        public string app { get; set; }
        public string apm { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public int Id_rol { get; set; }
    
        public virtual Roles Roles { get; set; }

        internal static void WriteLine(string v)
        {
            throw new NotImplementedException();
        }
    }
}
